#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app="$1"
app_dir="$PLUSHU_APPS_DIR/$app"
cidfile="$app_dir/proc/web.cid"

# kill the app when running
if [[ -f "$cidfile" ]]; then
    "$PLUSHU_ROOT/lib/plushook" docker-rm-cidfile "$cidfile"
fi
