#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

app=$1
app_dir=$PLUSHU_ROOT/apps/$app
cidfile=$app_dir/proc/web.cid

mkdir -p "$app_dir/proc"

# kill the app when running
if [[ -f "$cidfile" ]]; then
  oldcid=$(<"$cidfile")
  docker stop "$oldcid" > /dev/null && docker rm "$oldcid" > /dev/null
  rm "$cidfile"
fi

{ $PLUSHU_ROOT/lib/runhook run-app-docker-opts "$app";
  printf '%s /start web\n' "$(<"$app_dir/release.iid")"; } |
  xargs -x docker run -d --cidfile="$cidfile" -e PORT=5000 --expose=5000

$PLUSHU_ROOT/lib/runhook vhost "$app"
