#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

app_dir=$PLUSHU_ROOT/apps/$1
cidfile=$app_dir/proc/web.cid

# kill the app when running
if [[ -f "$cidfile" ]]; then
  oldcid=$(<"$cidfile")
  docker stop "$oldcid" > /dev/null && docker rm "$oldcid" > /dev/null
  rm "$cidfile"
fi

dockerargs=`$PLUSHU_ROOT/lib/runhook run-app-docker-args $1`
docker run -d --cidfile="$cidfile" -p 5000 -e PORT=5000 $dockerargs \
  $(<"$app_dir/release.iid") /start web

$PLUSHU_ROOT/lib/runhook vhost $1
