#!/usr/bin/env bash
set -eo pipefail; [[ $PLUSHU_TRACE ]] && set -x

app=$1
app_dir=$PLUSHU_ROOT/apps/$app
cidfile=$app_dir/proc/web.cid

# kill the app when running
if [[ -f "$cidfile" ]]; then
  oldcid=$(<"$cidfile")
  docker stop "$oldcid" > /dev/null && docker rm "$oldcid" > /dev/null
  rm "$cidfile"
fi

($PLUSHU_ROOT/lib/runhook run-app-docker-args "$app";
  echo "$(<$app_dir/release.iid) /start web") |
  xargs docker run -d --cidfile="$cidfile" -p 5000 -e PORT=5000

port=$(docker port $(<"$cidfile") 5000 | sed 's/0.0.0.0://')
echo "$port" > "$app_dir/PORT"
$PLUSHU_ROOT/lib/runhook vhost "$app" "$port"
