#!/usr/bin/env bash
set -eo pipefail; [[ -n "$PLUSHU_TRACE" ]] && set -x

app=$1
app_dir=$PLUSHU_APPS_DIR/$app

# If there's a release to run
if [[ -f "$app_dir/release.iid" ]]; then

  cidfile=$app_dir/proc/web.cid

  mkdir -p "$app_dir/proc"

  # kill the app when running
  if [[ -f "$cidfile" ]]; then
    oldcid=$(<"$cidfile")
    docker stop "$oldcid" > /dev/null && docker rm "$oldcid" > /dev/null
    rm "$cidfile"
  fi

  { "$PLUSHU_ROOT/lib/plushook" run-app-docker-opts "$app";
    printf '\n%s /start web\n' "$(<"$app_dir/release.iid")"; } |
    xargs -x docker run -d -e PORT=5000 --expose=5000 >"$cidfile"

  "$PLUSHU_ROOT/lib/plushook" vhost-app "$app"
fi
